# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'fr'
    app.image_directory: '%kernel.project_dir%/public/%env(IMAGE_DIR_NAME)%'
    app.avatar_directory: '%kernel.project_dir%/public/%env(AVATAR_DIR_NAME)%'
    app.per_page_comment: '%env(PER_PAGE_COMMENT)%'
    app.per_page_trick: '%env(PER_PAGE_TRICK)%'
    app.secret: '%env(APP_SECRET)%'
    app.contactEmail: '%env(APP_CONTACT_EMAIL)%'
    app.contactName: '%env(APP_CONTACT_NAME)%'
    

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $avatarDirectory: '%app.avatar_directory%'
            $imageDirectory: '%app.image_directory%'
            $projectDir: '%kernel.project_dir%'
            $perPageComment: '%app.per_page_comment%'
            $perPageTrick: '%app.per_page_trick%'
            

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Twig\ImageExtension:
        arguments:
            $avatarDirectory: '%env(AVATAR_DIR_NAME)%'
            $imageDirectory: '%env(IMAGE_DIR_NAME)%'
    
    App\Security\EmailVerifier:
        arguments:
            $secret: '%app.secret%'
            $contactEmail: '%app.contactEmail%'
            $contactName: '%app.contactName%'
    
    App\Security\ResetPasswordHelper:
        arguments:
            $contactEmail: '%app.contactEmail%'
            $contactName: '%app.contactName%'
            $secret: '%app.secret%'
